/*
*   TEXT AND PLAYER COLOURS
*/

#define COLOUR_RED                  0xFF0000FF
#define COLOUR_DARKRED              0x990000FF
#define COLOUR_ORANGE               0xFF6A00FF
#define COLOUR_YELLOW               0xFFD800FF
#define COLOUR_GREEN                0x00A813FF
#define COLOUR_SPRUCE               0x005409FF
#define COLOUR_SKYBLUE              0x1CA0FFFF
#define COLOUR_BLUE                 0x0026FFFF
#define COLOUR_DARKBLUE             0x001172FF
#define COLOUR_NAVYBLUE             0x0C4670FF
#define COLOUR_VIOLET               0xB200FFFF
#define COLOUR_DARKVIOLET           0x580082FF
#define COLOUR_LIGHTPURPLE          0xC891FFFF
#define COLOUR_PURPLE               0x664A82FF
#define COLOUR_PINK                 0xFF00BBFF
#define COLOUR_WHITE                0xFFFFFFFF
#define COLOUR_LIGHTGREY            0xCCCCCCFF
#define COLOUR_GREY                 0x999999FF
#define COLOUR_DARKGREY             0x444444FF
#define COLOUR_BLACK                0x000000FF
#define COLOUR_SYNTAX               0xFFCA4FFF
#define COLOUR_LABEL_CASINO         0x008989FF
#define COLOUR_LABEL_FOOD           0x87BC00FF
#define COLOUR_LABEL_HOUSE          0x990084FF
#define COLOUR_LABEL_MUNICIPAL      0x003860FF
#define COLOUR_LABEL_SHOP           0x31A500FF
